### ISSUE TITLE
Filter results

### ISSUE THREAD

**Issue by Chaphasilor** [micalevisk/inquirer-fs-selector#10]
Hey, I was wondering if it's somehow possible to filter the files and directories shown to the user?  
E.g. using a function that receives an object (`{isDirectoy, isFile, path}`) and returns a boolean.

The plugin itself is really nice, but I'm specifically trying to disable directory selection because my CLI only works with files, and this seems to be the most flexible option.

Of course, a simple `canSelectDirectory` option would also do the trick (although not as flexible for other use cases) \^\^

**Comment by micalevisk** [comment]
Sorry for the late response, I didn't get notified. This feature will be available on `1.4.0` as soon I manage to publish it on NPM lol (due to this https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/)

![image](https://user-images.githubusercontent.com/13461315/137828953-cedbbbd8-13d8-40d5-9d65-486e8a452c69.png)

btw I choose to avoid allocating literal objects every time (one for each item) just for this feat, thus the interface is

```
(isDirectory: boolean, isFile: boolean, fullPath: string) => boolean
```

**Comment by Chaphasilor** [comment]
> Sorry for the late response, I didn't get notified. This feature will be available on `1.4.0` as soon I manage to publish it on NPM lol 

No rush! :)  
I can probably just clone the main branch and pack it up with npm for testing locally, right?

> btw I choose to avoid allocating literal objects every time (one for each item) just for this feat, thus the interface is
> 
> ```
> (isDirectory: boolean, isFile: boolean, fullPath: string) => boolean
> ```

yeah that makes sense, no idea why I used object notation \^\^ 

Thanks a ton for implementing this this quickly (after becoming aware of it) <3

I'll try to test it this week(end) and let you know how it goes!

**Comment by micalevisk** [comment]
> I can probably just clone the main branch and pack it up with npm for testing locally, right?

or you can do this instead:

```bash
npm i github:micalevisk/inquirer-fs-selector
``` 

```js
const inquirer = require("inquirer")

inquirer.registerPrompt("directory", require("inquirer-fs-selector"))

inquirer.prompt([{
  type: "directory",
  name: "fs",
  message: "Choose a file or directory",
  basePath: "./",
  options: {
    showItem: (isDirectory, isFile, fullPath) => true,
    canSelectFile: true,
  }
}]).then(function(answers) {
  console.log(answers.fs)
});
```

**Comment by micalevisk** [comment]
btw, what do you think of `displayItem` instead of `showItem`? I'm open to suggestion because I didn't released it yet

**Comment by Chaphasilor** [comment]
> btw, what do you think of `displayItem` instead of `showItem`? I'm open to suggestion because I didn't released it yet

both work, no preference either way...  
`includeItem` would be another possibility.

I'll play around with it now and see how it goes :)

**Comment by Chaphasilor** [comment]
Hmm, I was under the assumption that `.` and `..` would be included in the list of items that are passed to the `showItem` function, so that I could filter out the current directory `.`, which was my initial plan.  
This could of course be done with a simple flag, but the filter function would be more flexible and I'm sure others have a use case for it.

I'm thinking about replacing the `isDirectory` param with `isCurrentDirectory` (and using `isFile === false` for dirs), but maybe you have a better idea?

Edit: `/path/to/current/dir/.` and `/path/to/current/dir/..` could also work...

**Comment by micalevisk** [comment]
the way this package was implemented, the `.` and `..` are special, and always are returned. I think this is feasible tho, but it implies changing more things. You could try to implement this in the meantime (and open a PR, if you succeed)

https://github.com/micalevisk/inquirer-fs-selector/blob/56921b16d1b5b8ca2a4a737847a75dfb670ec30b/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L406-L421

https://github.com/micalevisk/inquirer-fs-selector/blob/56921b16d1b5b8ca2a4a737847a75dfb670ec30b/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L484

---

> I'm thinking about replacing the `isDirectory` param with `isCurrentDirectory` (and using `isFile === false` for dirs), but maybe you have a better idea?

I didn't understand well what is the purpose of `isCurrentDirectory`. can you elaborate a bit?

<blockquote><img src="https://opengraph.githubassets.com/97101a40412aab651e6807eb431b10e3434aff533e5bc3b2c80bbff2d211c92b/micalevisk/inquirer-fs-selector" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/micalevisk/inquirer-fs-selector">inquirer-fs-selector/index.js at 56921b16d1b5b8ca2a4a737847a75dfb670ec30b · micalevisk/inquirer-fs-selector</a></strong></div><div>A filesystem prompt selector for Inquirer.js package. - inquirer-fs-selector/index.js at 56921b16d1b5b8ca2a4a737847a75dfb670ec30b · micalevisk/inquirer-fs-selector</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/97101a40412aab651e6807eb431b10e3434aff533e5bc3b2c80bbff2d211c92b/micalevisk/inquirer-fs-selector" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/micalevisk/inquirer-fs-selector">inquirer-fs-selector/index.js at 56921b16d1b5b8ca2a4a737847a75dfb670ec30b · micalevisk/inquirer-fs-selector</a></strong></div><div>A filesystem prompt selector for Inquirer.js package. - inquirer-fs-selector/index.js at 56921b16d1b5b8ca2a4a737847a75dfb670ec30b · micalevisk/inquirer-fs-selector</div></blockquote>

**Comment by Chaphasilor** [comment]
> I didn't understand well what is the purpose of isCurrentDirectory. can you elaborate a bit?

basically, return the current directory (`.`) as the full path `/path/to/current/dir` and set `isCurrentDirectory` to `true`, so that it is clear that this isn't just any dir. But it's a rather unelegant solution...

**Comment by Chaphasilor** [comment]
I think simply moving the `unshift()`s into the `getDirectoryContent()` function should do the trick :)

But there's still the topic of marking the special dirs, what do you think about this approach:
> `/path/to/current/dir/.` and `/path/to/current/dir/..` could also work...

so with the `.` and `..` appended at the end? This is even a valid path (at least on Windows, but probably linux too)

Edit: Oh and if you give the green light I could give you a PR in the coming days :D

**Comment by micalevisk** [comment]
> I could filter out the current directory `.`

but if this dir is not prompted, end-users won't be able to select any dir, just files. Is this what you're looking for?

**Comment by Chaphasilor** [comment]
> > I could filter out the current directory `.`
> 
> but if this dir is not prompted, end-users won't be able to select any dir, just files. Is this what you're looking for?

Yes, like I've said in the issue description, my tool only works on files, so I want to prevent users from picking directories.

I just thought a more general solution (the item filter) wouldn't hurt :)

**Comment by micalevisk** [comment]
alright

You can implement this and open a PR ^^

**Comment by Chaphasilor** [comment]
There's your PR 😇

**Comment by micalevisk** [comment]
I renamed `showItem` to `shouldDisplayItem`, btw

**Comment by micalevisk** [comment]
I still don't know how to circumvent that NPM error on `npm publish` :/

I've published another package just fine recently, but with this one is I'm getting `426 Upgrade Required - PUT http://registry.npmjs.org/inquirer-fs-selector` and I don't know why, tbh

**Comment by Chaphasilor** [comment]
> I've published another package just fine recently, but with this one is I'm getting `426 Upgrade Required - PUT http://registry.npmjs.org/inquirer-fs-selector` and I don't know why, tbh 

could it be that you need to replace that `http` with `https` somewhere, like your `package.json`?  
You could also try using GitHub Actions to publish the package, that might work 🤔

**Comment by micalevisk** [comment]
> You could also try using GitHub Actions

I've a GHA to publish upon new tag already. 

You were right! I didn't remember that the `package.json` has this registry in there XD It is published now!
